name: vpn4k
description: "VPN by 4aika_M"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  stroke_text: ^1.0.0
  tray_manager: ^0.5.3
  flutter_launcher_icons: ^0.14.4
  window_manager: ^0.5.1
  wireguard_flutter_plus: ^1.0.6
  fl_chart: ^1.2.0
  url_launcher: ^6.3.2
  file_picker: ^11.0.2
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png
    - assets/icon_in_progress.svg
    - assets/icon_active.svg
    - assets/icon_inactive.svg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "/Users/matvey/Documents/dev/flutter/vpn4k/assets/icon/icon.png"